<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Cari Rata-rata Bilangan</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <h1>Cari Rata-rata Bilangan</h1>
    <form method="post" action="proses1.php">
        Masukkan Banyaknya Bilangan <input type="text" name="n" />
        <input type="submit" name="submit" value="Submit" />
    </form>
</body>
</html>